
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           52923
     no. of nonzeroes in lower triangle of a =         2219001
     no. of nonzeroes in the factor l        =        14363130
     ratio of nonzeroes in factor (min/max)  =          0.5100
     number of super nodes                   =            2069
     maximum order of a front matrix         =            1506
     maximum size of a front matrix          =         1134771
     maximum size of a front trapezoid       =          623484
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      7.3242D+09
     no. of floating point ops for solve     =      5.3706D+07
     ratio of flops for factor (min/max)     =          0.7605
     ratio of allocated memory (max/min)     =          1.9953
     number of positive pivots               =           52923
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.004431
     time (cpu & wall) for ordering          =        0.078125        0.079310
     time (cpu & wall) for other matrix prep =        0.015625        0.017475
     time (cpu & wall) for value input       =        0.000000        0.006290
     time (cpu & wall) for matrix distrib.   =        0.046875        0.051671
     time (cpu & wall) for numeric factor    =        0.140625        0.166164
     computational rate (gflops) for factor  =       52.082886       44.077953

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         67911.        1. MB
                95-   1        131072.        1. MB        119945.        1. MB
                95-   2        163840.        1. MB        152974.        1. MB
                95-   3        229376.        2. MB        211290.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        622592.        5. MB        552120.        4. MB


  Solver Memory allocated on core    0       =       39.744 MB
  Solver Memory allocated on core    1       =       60.435 MB
  Solver Memory allocated on core    2       =       52.134 MB
  Solver Memory allocated on core    3       =       79.302 MB
  Total Solver Memory allocated by all cores =      231.616 MB

