
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           26226
     no. of nonzeroes in lower triangle of a =          859662
     no. of nonzeroes in the factor l        =         5207973
     ratio of nonzeroes in factor (min/max)  =          0.9072
     number of super nodes                   =            1097
     maximum order of a front matrix         =             717
     maximum size of a front matrix          =          257403
     maximum size of a front trapezoid       =          143052
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.3779D+09
     no. of floating point ops for solve     =      1.9140D+07
     ratio of flops for factor (min/max)     =          0.9178
     ratio of allocated memory (max/min)     =          1.1361
     number of positive pivots               =           26226
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001913
     time (cpu & wall) for ordering          =        0.031250        0.029222
     time (cpu & wall) for other matrix prep =        0.000000        0.003471
     time (cpu & wall) for value input       =        0.015625        0.004153
     time (cpu & wall) for matrix distrib.   =        0.015625        0.020738
     time (cpu & wall) for numeric factor    =        0.046875        0.036497
     computational rate (gflops) for factor  =       29.395633       37.754033

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         66980.        1. MB
                95-   1         98304.        1. MB         65625.        1. MB
                95-   2         98304.        1. MB         72882.        1. MB
                95-   3         98304.        1. MB         67341.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        272828.        2. MB


  Solver Memory allocated on core    0       =       21.679 MB
  Solver Memory allocated on core    1       =       20.595 MB
  Solver Memory allocated on core    2       =       23.398 MB
  Solver Memory allocated on core    3       =       20.693 MB
  Total Solver Memory allocated by all cores =       86.365 MB

