
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           52923
     no. of nonzeroes in lower triangle of a =         2219001
     no. of nonzeroes in the factor l        =        14308734
     ratio of nonzeroes in factor (min/max)  =          0.4887
     number of super nodes                   =            2078
     maximum order of a front matrix         =            1512
     maximum size of a front matrix          =         1143828
     maximum size of a front trapezoid       =          590439
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      7.1858D+09
     no. of floating point ops for solve     =      5.3438D+07
     ratio of flops for factor (min/max)     =          0.8267
     ratio of allocated memory (max/min)     =          2.1433
     number of positive pivots               =           52923
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.015625        0.003344
     time (cpu & wall) for ordering          =        0.062500        0.064603
     time (cpu & wall) for other matrix prep =        0.000000        0.010105
     time (cpu & wall) for value input       =        0.000000        0.004001
     time (cpu & wall) for matrix distrib.   =        0.062500        0.056331
     time (cpu & wall) for numeric factor    =        0.156250        0.162019
     computational rate (gflops) for factor  =       45.989217       44.351709
     time (cpu & wall) for numeric solve     =        0.015625        0.009191
     computational rate (gflops) for solve   =        3.420056        5.813954
     effective I/O rate (GB/sec) for solve   =       12.741713       21.660385

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         69473.        1. MB
                95-   1        131072.        1. MB        119997.        1. MB
                95-   2        163840.        1. MB        143806.        1. MB
                95-   3        229376.        2. MB        221837.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:        622592.        5. MB        555113.        4. MB


  Solver Memory allocated on core    0       =       38.365 MB
  Solver Memory allocated on core    1       =       56.846 MB
  Solver Memory allocated on core    2       =       49.869 MB
  Solver Memory allocated on core    3       =       82.228 MB
  Total Solver Memory allocated by all cores =      227.308 MB

