
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           74270
     no. of nonzeroes in lower triangle of a =         1177716
     no. of nonzeroes in the factor l        =         6996060
     ratio of nonzeroes in factor (min/max)  =          0.8203
     number of super nodes                   =            3885
     maximum order of a front matrix         =             467
     maximum size of a front matrix          =          109278
     maximum size of a front trapezoid       =           71442
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      9.0474D+08
     no. of floating point ops for solve     =      2.4538D+07
     ratio of flops for factor (min/max)     =          0.8200
     ratio of allocated memory (max/min)     =          1.3339
     number of positive pivots               =           74270
     number of negative pivots               =               0
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      0.0000D+00
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.006149
     time (cpu & wall) for ordering          =        0.359375        0.362707
     time (cpu & wall) for other matrix prep =        0.046875        0.038843
     time (cpu & wall) for value input       =        0.015625        0.007355
     time (cpu & wall) for matrix distrib.   =        0.046875        0.046390
     time (cpu & wall) for numeric factor    =        0.046875        0.058403
     computational rate (gflops) for factor  =       19.301177       15.491479

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        294912.        2. MB        264564.        2. MB
                95-   1        360448.        3. MB        340605.        3. MB
                95-   2        262144.        2. MB        238057.        2. MB
                95-   3        294912.        2. MB        282216.        2. MB

                -------     ----------     --------     ----------     --------
                Totals:       1212416.        9. MB       1125442.        9. MB


  Solver Memory allocated on core    0       =       38.893 MB
  Solver Memory allocated on core    1       =       40.377 MB
  Solver Memory allocated on core    2       =       30.269 MB
  Solver Memory allocated on core    3       =       35.053 MB
  Total Solver Memory allocated by all cores =      144.592 MB

